### Лабораторна робота №5

In [1]:
N = ord("M") % 15 + 1
print("Варіант -",N)

Варіант - 3


## Завдання №1 - Виконати набір вправ двома способами та підрахувати час виконання

#### Вправа №1

In [9]:
import numpy as np
import time
import random

In [10]:
def create_diag_numpy(n):
    
    matrix = np.zeros((n, n), dtype=int)
    
    diagonal_values = np.arange(1, n + 1)
    
    np.fill_diagonal(matrix, diagonal_values)
    
    return matrix

In [11]:
def create_diag_python(n):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(i + 1)
            else:
                row.append(0)
        matrix.append(row)
    return matrix

In [12]:
def task1():
    n = int(input("Введіть розмір n: "))

    start_time = time.perf_counter()
    matrix_numpy = create_diag_numpy(n)
    end_time = time.perf_counter()
    numpy_time = end_time - start_time

    start_time = time.perf_counter()
    matrix_python = create_diag_python(n)
    end_time = time.perf_counter()
    python_time = end_time - start_time

    print("Матриця (NumPy):")
    print(matrix_numpy)

    print("Матриця (списки/цикли):")
    for row in matrix_python:
        print(row)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")


In [13]:
task1()

Введіть розмір n:  5


Матриця (NumPy):
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Матриця (списки/цикли):
[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
Час NumPy: 0.000048 с
Час списки/цикли: 0.000008 с
Варіант зі звичайними циклами працює швидше


#### Вправа №3

In [14]:
def create_matrix_numpy(n, m, r, c):
    matrix = np.ones((n, m), dtype=int)
    matrix[r - 1::r, :] = 0
    matrix[:, c - 1::c] = 0
    return matrix

In [15]:
def create_matrix_python(n, m, r, c):
    matrix = []
    for i in range(1, n + 1):
        row = []
        for j in range(1, m + 1):
            if i % r == 0 or j % c == 0:
                row.append(0)
            else:
                row.append(1)
        matrix.append(row)
    return matrix

In [16]:
def task3():
    n = int(input("Введіть кількість рядків n: "))
    m = int(input("Введіть кількість стовпчиків m: "))
    r = int(input("Введіть r (кожний r-й рядок нульовий): "))
    c = int(input("Введіть c (кожний c-й стовпчик нульовий): "))

    start_time = time.perf_counter()
    matrix_numpy = create_matrix_numpy(n, m, r, c)
    end_time = time.perf_counter()
    numpy_time = end_time - start_time

    start_time = time.perf_counter()
    matrix_python = create_matrix_python(n, m, r, c)
    end_time = time.perf_counter()
    python_time = end_time - start_time

    print("Матриця (NumPy):")
    print(matrix_numpy)

    print("Матриця (списки/цикли):")
    for row in matrix_python:
        print(row)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")


In [17]:
task3()

Введіть кількість рядків n:  5
Введіть кількість стовпчиків m:  5
Введіть r (кожний r-й рядок нульовий):  2
Введіть c (кожний c-й стовпчик нульовий):  3


Матриця (NumPy):
[[1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]]
Матриця (списки/цикли):
[1, 1, 0, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 0, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 0, 1, 1]
Час NumPy: 0.000024 с
Час списки/цикли: 0.000009 с
Варіант зі звичайними циклами працює швидше


#### Вправа №6

In [18]:
def read_int_array():
    line = input("Введіть елементи масиву через пробіл: ")
    if not line.strip():
        return []
    numbers = list(map(int, line.split()))
    return numbers

In [19]:
def replace_non_zero_numpy(numbers):
    arr = np.array(numbers, dtype=int)
    arr[arr != 0] = -1
    return arr

In [20]:
def replace_non_zero_python(numbers):
    result = []
    for value in numbers:
        if value != 0:
            result.append(-1)
        else:
            result.append(0)
    return result

In [21]:
def task6():
    numbers = read_int_array()

    start_time = time.perf_counter()
    result_numpy = replace_non_zero_numpy(numbers)
    end_time = time.perf_counter()
    numpy_time = end_time - start_time

    start_time = time.perf_counter()
    result_python = replace_non_zero_python(numbers)
    end_time = time.perf_counter()
    python_time = end_time - start_time

    print("Результат (NumPy):")
    print(result_numpy)

    print("Результат (списки/цикли):")
    print(result_python)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")


In [39]:
task6()

Введіть елементи масиву через пробіл:  1 2 3 4 5 6 0 0 0 -1


Результат (NumPy):
[-1 -1 -1 -1 -1 -1  0  0  0 -1]
Результат (списки/цикли):
[-1, -1, -1, -1, -1, -1, 0, 0, 0, -1]
Час NumPy: 0.000135 с
Час списки/цикли: 0.000005 с
Варіант зі звичайними циклами працює швидше


#### Вправа №7

In [22]:
def replace_zero_numpy(numbers):
    arr = np.array(numbers, dtype=int)
    arr[arr == 0] = -1
    return arr

In [23]:
def replace_zero_python(numbers):
    result = []
    for value in numbers:
        if value == 0:
            result.append(-1)
        else:
            result.append(value)
    return result

In [24]:
def task7():
    numbers = read_int_array()

    start_time = time.perf_counter()
    result_numpy = replace_zero_numpy(numbers)
    end_time = time.perf_counter()
    numpy_time = end_time - start_time

    start_time = time.perf_counter()
    result_python = replace_zero_python(numbers)
    end_time = time.perf_counter()
    python_time = end_time - start_time

    print("Результат (NumPy):")
    print(result_numpy)

    print("Результат (списки/цикли):")
    print(result_python)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")


In [43]:
task7()

Введіть елементи масиву через пробіл:  0 0 0 1 2 3 4 5 -1


Результат (NumPy):
[-1 -1 -1  1  2  3  4  5 -1]
Результат (списки/цикли):
[-1, -1, -1, 1, 2, 3, 4, 5, -1]
Час NumPy: 0.000078 с
Час списки/цикли: 0.000005 с
Варіант зі звичайними циклами працює швидше


#### Вправа №8

In [25]:
def count_zero_non_zero_numpy(numbers):
    arr = np.array(numbers, dtype=int)
    zero_count = np.count_nonzero(arr == 0)
    non_zero_count = np.count_nonzero(arr != 0)
    return zero_count, non_zero_count

In [26]:
def count_zero_non_zero_python(numbers):
    zero_count = 0
    non_zero_count = 0
    for value in numbers:
        if value == 0:
            zero_count += 1
        else:
            non_zero_count += 1
    return zero_count, non_zero_count

In [27]:
def task8():
    numbers = read_int_array()

    start_time = time.perf_counter()
    zero_numpy, non_zero_numpy = count_zero_non_zero_numpy(numbers)
    end_time = time.perf_counter()
    numpy_time = end_time - start_time

    start_time = time.perf_counter()
    zero_python, non_zero_python = count_zero_non_zero_python(numbers)
    end_time = time.perf_counter()
    python_time = end_time - start_time

    print("Результат (NumPy):")
    print("Нульових:", zero_numpy, "Ненульових:", non_zero_numpy)

    print("Результат (списки/цикли):")
    print("Нульових:", zero_python, "Ненульових:", non_zero_python)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")


In [48]:
task8()

Введіть елементи масиву через пробіл:   1 2 3 4 5 6 7 0 -1


Результат (NumPy):
Нульових: 1 Ненульових: 8
Результат (списки/цикли):
Нульових: 1 Ненульових: 8
Час NumPy: 0.000043 с
Час списки/цикли: 0.000003 с
Варіант зі звичайними циклами працює швидше


#### Вправа №11

In [28]:
def frame_numpy(n):
    matrix = np.ones((n, n), dtype=int)
    matrix[0, :] = 0
    matrix[-1, :] = 0
    matrix[:, 0] = 0
    matrix[:, -1] = 0
    return matrix

In [29]:
def frame_python(n):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == 0 or j == 0 or i == n - 1 or j == n - 1:
                row.append(0)
            else:
                row.append(1)
        matrix.append(row)
    return matrix

In [30]:
def task11():
    n = int(input("Введіть розмір n: "))

    start = time.perf_counter()
    matrix_numpy = frame_numpy(n)
    end = time.perf_counter()
    numpy_time = end - start

    start = time.perf_counter()
    matrix_python = frame_python(n)
    end = time.perf_counter()
    python_time = end - start

    print("Матриця (NumPy):")
    print(matrix_numpy)

    print("Матриця (списки/цикли):")
    for row in matrix_python:
        print(row)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")

In [55]:
task11()

Введіть розмір n:  5


Матриця (NumPy):
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
Матриця (списки/цикли):
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 0, 0, 0, 0]
Час NumPy: 0.000034 с
Час списки/цикли: 0.000013 с
Варіант зі звичайними циклами працює швидше


#### Вправа №16

In [31]:
def cut_vector_numpy(n):
    vec = np.arange(0, n + 1, dtype=int)
    lower = n / 4
    upper = 3 * n / 4
    mask = (vec > lower) & (vec < upper)
    vec[mask] = 0
    return vec

In [32]:
def cut_vector_python(n):
    vec = list(range(0, n + 1))
    lower = n / 4
    upper = 3 * n / 4
    for i in range(len(vec)):
        if vec[i] > lower and vec[i] < upper:
            vec[i] = 0
    return vec

In [33]:
def task16():
    n = int(input("Введіть n: "))

    start = time.perf_counter()
    vec_numpy = cut_vector_numpy(n)
    end = time.perf_counter()
    numpy_time = end - start

    start = time.perf_counter()
    vec_python = cut_vector_python(n)
    end = time.perf_counter()
    python_time = end - start

    print("Вектор (NumPy):")
    print(vec_numpy)

    print("Вектор (списки/цикли):")
    print(vec_python)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")

In [59]:
task16()

Введіть n:  5


Вектор (NumPy):
[0 1 0 0 4 5]
Вектор (списки/цикли):
[0, 1, 0, 0, 4, 5]
Час NumPy: 0.000166 с
Час списки/цикли: 0.000009 с
Варіант зі звичайними циклами працює швидше


#### Вправа №18

In [34]:
def unique_count_numpy(n):
    vec = np.random.randint(0, 100, size=n)
    unique_values = np.unique(vec)
    return vec, len(unique_values)

In [35]:
def unique_count_python(n):
    vec = [random.randint(0, 99) for _ in range(n)]
    unique_values = set(vec)
    return vec, len(unique_values)

In [36]:
def task18():
    n = int(input("Введіть розмір вектора n: "))

    start = time.perf_counter()
    vec_numpy, count_numpy = unique_count_numpy(n)
    end = time.perf_counter()
    numpy_time = end - start

    start = time.perf_counter()
    vec_python, count_python = unique_count_python(n)
    end = time.perf_counter()
    python_time = end - start

    print("Вектор (NumPy):")
    print(vec_numpy)
    print("Кількість унікальних (NumPy):", count_numpy)

    print("Вектор (списки/цикли):")
    print(vec_python)
    print("Кількість унікальних (списки/цикли):", count_python)

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")

In [72]:
task18()

Введіть розмір вектора n:  5


Вектор (NumPy):
[80 68 29 28 98]
Кількість унікальних (NumPy): 5
Вектор (списки/цикли):
[35, 94, 34, 4, 90]
Кількість унікальних (списки/цикли): 5
Час NumPy: 0.000135 с
Час списки/цикли: 0.000028 с
Варіант зі звичайними циклами працює швидше


#### Вправа №19

In [40]:
def interval_vector_numpy(n):
    vec = np.linspace(0.0, 1.0, n + 2, endpoint=True)[1:-1]
    return vec

In [41]:
def interval_vector_python(n):
    step = 1.0 / (n + 1)
    vec = []
    for i in range(1, n + 1):
        value = i * step
        vec.append(value)
    return vec

In [42]:
def task19():
    n = int(input("Введіть розмір вектора n: "))

    start = time.perf_counter()
    vec_numpy = interval_vector_numpy(n)
    end = time.perf_counter()
    numpy_time = end - start

    start = time.perf_counter()
    vec_python = interval_vector_python(n)
    end = time.perf_counter()
    python_time = end - start

    print("Вектор (NumPy), 3 знаки після коми:")
    print([f"{x:.3f}" for x in vec_numpy])

    print("Вектор (списки/цикли), 3 знаки після коми:")
    print([f"{x:.3f}" for x in vec_python])

    print(f"Час NumPy: {numpy_time:.6f} с")
    print(f"Час списки/цикли: {python_time:.6f} с")

    if numpy_time < python_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_time > python_time:
        print("Варіант зі звичайними циклами працює швидше")
    else:
        print("Час виконання обох варіантів приблизно однаковий.")

In [43]:
task19()

Введіть розмір вектора n:  5


Вектор (NumPy), 3 знаки після коми:
['0.167', '0.333', '0.500', '0.667', '0.833']
Вектор (списки/цикли), 3 знаки після коми:
['0.167', '0.333', '0.500', '0.667', '0.833']
Час NumPy: 0.000095 с
Час списки/цикли: 0.000004 с
Варіант зі звичайними циклами працює швидше


## Завдання №2 - Розв’язати систему за допомогою формул Крамера і виконати перевірки

\begin{cases}
x_1 + 2x_2 + 3x_3 + 4x_4 = 5,\\
2x_1 + x_2 + 2x_3 + 3x_4 = 1,\\
3x_1 + 2x_2 + x_3 + 2x_4 = 1,\\
4x_1 + 3x_2 + 2x_3 + x_4 = -5
\end{cases}

In [44]:
def solve_linear_system_cramers_rule(coefficient_matrix, constant_vector):
    determinant_main_matrix = np.linalg.det(coefficient_matrix)

    if abs(determinant_main_matrix) < 1e-12:
        raise ValueError("Визначник головної матриці близький до нуля, система може не мати єдиного розв'язку.")

    number_of_unknowns = coefficient_matrix.shape[0]
    solution_vector = np.zeros(number_of_unknowns, dtype=float)

    for column_index in range(number_of_unknowns):

        replaced_matrix = coefficient_matrix.copy()
        replaced_matrix[:, column_index] = constant_vector

        determinant_replaced_matrix = np.linalg.det(replaced_matrix)
        solution_vector[column_index] = determinant_replaced_matrix / determinant_main_matrix

    return solution_vector

In [45]:
def task_linear_system():

    coefficient_matrix = np.array([[1, 2, 3, 4],
                                   [2, 1, 2, 3],
                                   [3, 2, 1, 2],
                                   [4, 3, 2, 1]], dtype=float)

    constant_vector = np.array([5, 1, 1, -5], dtype=float)

    print("Матриця коефіцієнтів (A):")
    print(coefficient_matrix)
    print("Вектор вільних членів (b):")
    print(constant_vector)

    cramers_solution = solve_linear_system_cramers_rule(coefficient_matrix, constant_vector)
    print("\nРозв'язок за формулами Крамера:")
    print(cramers_solution)

    left_side_values = coefficient_matrix @ cramers_solution
    print("\nПеревірка через матричне множення A @ x:")
    print("A @ x =", left_side_values)
    print("b =", constant_vector)
    print("Чи співпадає A @ x з b? ->", np.allclose(left_side_values, constant_vector))

    inverse_matrix = np.linalg.inv(coefficient_matrix)
    inverse_solution = inverse_matrix @ constant_vector
    print("\nРозв'язок через обернену матрицю A^(-1) * b:")
    print(inverse_solution)

    solve_function_solution = np.linalg.solve(coefficient_matrix, constant_vector)
    print("\nРозв'язок через numpy.linalg.solve:")
    print(solve_function_solution)

    print("\nПорівняння розв'язків :") #(numpy.allclose)
    print("Крамер vs inverse:", np.allclose(cramers_solution, inverse_solution))
    print("Крамер vs solve  :", np.allclose(cramers_solution, solve_function_solution))
    print("inverse vs solve :", np.allclose(inverse_solution, solve_function_solution))


In [46]:
task_linear_system()

Матриця коефіцієнтів (A):
[[1. 2. 3. 4.]
 [2. 1. 2. 3.]
 [3. 2. 1. 2.]
 [4. 3. 2. 1.]]
Вектор вільних членів (b):
[ 5.  1.  1. -5.]

Розв'язок за формулами Крамера:
[-2.  2. -3.  3.]

Перевірка через матричне множення A @ x:
A @ x = [ 5.  1.  1. -5.]
b = [ 5.  1.  1. -5.]
Чи співпадає A @ x з b? -> True

Розв'язок через обернену матрицю A^(-1) * b:
[-2.  2. -3.  3.]

Розв'язок через numpy.linalg.solve:
[-2.  2. -3.  3.]

Порівняння розв'язків :
Крамер vs inverse: True
Крамер vs solve  : True
inverse vs solve : True


## Завдання №3 - Обчислити значення матричного виразу

$$2(A-B)(A^{2}+B)B$$


A=\begin{pmatrix}
5 & 1 & 7\\
-10 & -2 & 1\\
0 & 1 & 2
\end{pmatrix}
B=\begin{pmatrix}
2 & 4 & 1\\
3 & 1 & 0\\
7 & 2 & 1
\end{pmatrix}

In [47]:
def calculate_matrix_expression_numpy():

    matrix_A = np.array([[5, 1, 7],
                         [-10, -2, 1],
                         [0, 1, 2]], dtype=float)

    matrix_B = np.array([[2, 4, 1],
                         [3, 1, 0],
                         [7, 2, 1]], dtype=float)

    matrix_A_squared = matrix_A @ matrix_A      # A^2
    matrix_difference = matrix_A - matrix_B     # A - B
    matrix_sum = matrix_A_squared + matrix_B    # A^2 + B

    result_matrix = 2 * (matrix_difference @ matrix_sum)

    return result_matrix


In [48]:
def subtract_two_matrices(first_matrix, second_matrix):
    rows_count = len(first_matrix)
    columns_count = len(first_matrix[0])
    result_matrix = []

    for row_index in range(rows_count):
        new_row = []
        for column_index in range(columns_count):
            new_value = first_matrix[row_index][column_index] - second_matrix[row_index][column_index]
            new_row.append(new_value)
        result_matrix.append(new_row)

    return result_matrix


def add_two_matrices(first_matrix, second_matrix):
    rows_count = len(first_matrix)
    columns_count = len(first_matrix[0])
    result_matrix = []

    for row_index in range(rows_count):
        new_row = []
        for column_index in range(columns_count):
            new_value = first_matrix[row_index][column_index] + second_matrix[row_index][column_index]
            new_row.append(new_value)
        result_matrix.append(new_row)

    return result_matrix


def multiply_two_matrices(first_matrix, second_matrix):
    rows_count = len(first_matrix)
    common_size = len(second_matrix)
    columns_count = len(second_matrix[0])
    result_matrix = []

    for row_index in range(rows_count):
        new_row = []
        for column_index in range(columns_count):
            cell_sum = 0
            for common_index in range(common_size):
                cell_sum += first_matrix[row_index][common_index] * second_matrix[common_index][column_index]
            new_row.append(cell_sum)
        result_matrix.append(new_row)

    return result_matrix


def multiply_matrix_by_number(number_value, matrix):
    result_matrix = []
    for row in matrix:
        new_row = []
        for element in row:
            new_row.append(number_value * element)
        result_matrix.append(new_row)
    return result_matrix


def calculate_matrix_expression_with_loops():

    matrix_A = [[5, 1, 7],
                [-10, -2, 1],
                [0, 1, 2]]

    matrix_B = [[2, 4, 1],
                [3, 1, 0],
                [7, 2, 1]]

    matrix_A_squared = multiply_two_matrices(matrix_A, matrix_A)
    matrix_difference = subtract_two_matrices(matrix_A, matrix_B)
    matrix_sum = add_two_matrices(matrix_A_squared, matrix_B)

    product_matrix = multiply_two_matrices(matrix_difference, matrix_sum)
    final_result_matrix = multiply_matrix_by_number(2, product_matrix)

    return final_result_matrix


In [49]:
def task_matrix_expression():

    start_time = time.perf_counter()
    numpy_result = calculate_matrix_expression_numpy()
    end_time = time.perf_counter()
    numpy_execution_time = end_time - start_time

    start_time = time.perf_counter()
    loops_result = calculate_matrix_expression_with_loops()
    end_time = time.perf_counter()
    loops_execution_time = end_time - start_time

    print("\nРезультат (NumPy):")
    print(numpy_result)

    print("\nРезультат (списки та цикли):")
    for row in loops_result:
        print(row)

    loops_result_as_array = np.array(loops_result, dtype=float)
    print("\nЧи однакові результати? ->",
          np.allclose(numpy_result, loops_result_as_array))

    print(f"\nЧас виконання NumPy: {numpy_execution_time:.6f} с")
    print(f"Час виконання цикли : {loops_execution_time:.6f} с")

    if numpy_execution_time < loops_execution_time:
        print("Варіант з NumPy працює швидше.")
    elif numpy_execution_time > loops_execution_time:
        print("На цих розмірах матриць швидше спрацювали звичайні цикли.")
    else:
        print("Час виконання двох варіантів приблизно однаковий.")


In [50]:
task_matrix_expression()


Результат (NumPy):
[[ 228.  132.  798.]
 [-286. -336. -894.]
 [-190. -184. -562.]]

Результат (списки та цикли):
[228, 132, 798]
[-286, -336, -894]
[-190, -184, -562]

Чи однакові результати? -> True

Час виконання NumPy: 0.000102 с
Час виконання цикли : 0.000025 с
На цих розмірах матриць швидше спрацювали звичайні цикли.
